# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-09 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('maestro', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.Program'),
        ),
    ]
